# Generated by Django 5.1.2 on 2024-11-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_ordercart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderCart',
            new_name='CartItem',
        ),
    ]
