# Generated by Django 5.1.2 on 2024-11-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('view_history', 'can view history')]},
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
