# Generated by Django 5.1.2 on 2024-10-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_optcode_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optcode',
            name='code',
            field=models.PositiveIntegerField(verbose_name='کد تایید'),
        ),
    ]
